// Auth actions
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';


// Message actions
export const LOAD_THREAD_LIST_ATTEMPT = 'GET_MESSAGE_LIST_ATTEMPT';
export const LOAD_THREAD_LIST_FAILURE = 'GET_MESSAGE_LIST_FAILURE'
export const LOAD_THREAD_LIST_SUCCESS = 'GET_MESSAGE_LIST_SUCCESS';
