// Auth actions
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';


// Message actions
export const LOAD_THREAD_LIST_ATTEMPT = 'LOAD_THREAD_LIST_ATTEMPT';
export const LOAD_THREAD_LIST_FAILURE = 'LOAD_THREAD_LIST_FAILURE';
export const LOAD_THREAD_LIST_SUCCESS = 'LOAD_THREAD_LIST_SUCCESS';

export const LOAD_MESSAGES_ATTEMPT = 'LOAD_MESSAGES_ATTEMPT';
export const LOAD_MESSAGES_FAILURE = 'LOAD_MESSAGES_FAILURE';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';

export const SEND_MESSAGE_ATTEMPT = 'SEND_MESSAGE_ATTEMPT';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
